---
bitsblocks (11):
- bitcoin-maximalist
- bitcoin-whitepaper
- bitsblocks.github.io
- colored-coins-whitepaper
- crypto-bubbles
- crypto-facts
- ethereum
- ethereum-whitepaper
- get-rich-quick-bible
- islandcoin-whitepaper
- mastercoin-whitepaper
bitshilling (2):
- bitshilling
- bitshilling.tools
cryptocopycats (9):
- awesome-cryptocollectibles
- awesome-cryptokitties
- base32-alphabets
- bitcat
- copycats
- kitties
- kittyverse
- kittyverse.json
- media
openblockchains (20):
- awesome-blockchains
- awesome-cheezewizards
- awesome-coins
- awesome-ico-truths
- awesome-libra
- awesome-sha256
- awesome-tokens
- blockchain-whitepapers
- blockchain.lite.js
- blockchain.lite.rb
- centralbank
- ledger.lite.rb
- merkletree.rb
- peer-to-peer.rb
- programming-bitcoin-script
- programming-blockchains
- programming-cryptocollectibles
- programming-cryptocontracts
- tulipmania
- tulips
s6ruby (12):
- awesome-crypto
- ethereum-contracts
- pragmas
- redpaper
- ruby-to-michelson
- ruby-to-solidity
- safemath
- safestruct
- units-money
- units-time
- universum
- universum-contracts
viennacrypto (2):
- blockchain-whitepapers
- viennacrypto.github.io
