---
footballcsv (17):
- austria
- belgium
- cache.footballdata
- cache.internationals
- cache.leagues
- cache.soccerdata
- cache.soccerverse
- cache.updates
- deutschland
- england
- espana
- europe-champions-league
- footballcsv.github.io
- major-league-soccer
- mexico
- spec
- world
openfootball (41):
- africa-cup
- austria
- club-world-cup
- clubs
- confed-cup
- copa-america
- copa-libertadores
- copa-sudamericana
- deutschland
- docs
- england
- espana
- euro-cup
- europe
- europe-champions-league
- football.json
- fussball-de
- futbol-es
- help
- italy
- lang
- league-starter
- leagues
- mexico
- national-teams
- north-america-champions-league
- north-america-gold-cup
- opendata-theme
- openfootball.github.io
- players
- quick-starter
- schema
- schema.sql
- south-america
- spec
- stadiums
- women-euro-cup
- women-world-cup
- world
- world-cup
- world-cup.json
rsssf (7):
- austria
- brazil
- deutschland
- england
- espana
- rsssf.github.io
- spec
