---
geraldb (4):
- geraldb
- geraldb.github.io
- sandbox
- talks
yorobot (18):
- auto
- backup
- beer.db
- cache.csv
- cache.github
- football.csv
- football.db
- football.db.rsssf
- football.json
- logs
- planetjekyll
- rubyconf
- sport.db.more
- stage
- tipp3
- workflow
- world.db
- yorobot
austriacodes (5):
- austria.txt
- austriacodes.github.io
- awesome-austria
- showcase
- vienna.html
beerbook (3):
- beerbook.github.io
- calendar
- maps
beercsv (7):
- be-belgium
- build
- ca-canada
- de-deutschland
- statistics
- us-united-states
- world
beerkit (9):
- beer.api.js
- beer.db
- beer.db.admin
- beer.db.day
- beer.db.mobile
- beer.db.service
- beer.db.starter
- beer.js
- beerbook
beerlabels (2):
- beer.db.labels
- beer.db.labels.ruby
bibtxt (1):
- bibtxt.github.io
bigkorupto (3):
- awesome-nocode
- mammad-kabiri-uniqa
- sources
bitsblocks (11):
- bitcoin-maximalist
- bitcoin-whitepaper
- bitsblocks.github.io
- colored-coins-whitepaper
- crypto-bubbles
- crypto-facts
- ethereum
- ethereum-whitepaper
- get-rich-quick-bible
- islandcoin-whitepaper
- mastercoin-whitepaper
book-templates (4):
- beer
- bookfile
- football
- world
bookdesigns (4):
- book-epsilon
- book-git
- book-hamilton
- book-rust
chooseaconduct (1):
- chooseaconduct.github.io
cryptocopycats (17):
- awesome-cryptocollectibles
- awesome-cryptokitties-bubble
- awesome-mooncatrescue-bubble
- cache.kitties.json
- contracts
- copycats
- cryptocopycats.github.io
- design.mooncats
- kitties
- kittypedia
- kittyverse
- market.mooncatrescue
- media
- mooncatrescue
- mooncats
- programming-cryptokitties
- programming-mooncats
cryptopunksnotdead (21):
- ".github"
- awesome-24px
- awesome-cryptopunks-bubble
- cryptopunks
- cryptopunks-gui
- cryptopunksnotdead.github.io
- faq
- lets-go-programming-cryptopunks
- pixelart.js
- programming-cryptopunks
- punks.attributes
- punks.blocks
- punks.contracts
- punks.design
- punks.journal
- punks.market
- punks.readymade
- punks.spritesheet
- punks.starter
- punks.whitelabel
- punkweek
csvreader (1):
- csvreader
csvspecs (9):
- awesome-csv
- csv-hxl
- csv-json
- csv-meta
- csv-next
- csv-numerics
- csv-v10
- csv-v11
- csv-yaml
datatxt (2):
- awesome-yaml
- datatxt.github.io
drjekyllthemes (4):
- drjekyll
- drjekyllthemes.github.io
- test-theme
- themes
factbook (7):
- cache.factbook.json
- country-profiles
- factbook
- factbook.github.io
- factbook.json
- factbook.sql
- media
feedparser (2):
- feedparser
- feeds
feedreader (9):
- feedreader.github.io
- jekyll.planet.sample
- news.rb
- planet.rb
- planets
- pluto
- pluto.more.tools
- pluto.starter
- website.old
feedtxt (2):
- feedtxt
- feedtxt.github.io
footballbook (2):
- calendar
- footballbook.github.io
footballcsv (17):
- austria
- belgium
- cache.footballdata
- cache.internationals
- cache.leagues
- cache.soccerdata
- cache.soccerverse
- cache.updates
- deutschland
- england
- espana
- europe-champions-league
- footballcsv.github.io
- major-league-soccer
- mexico
- spec
- world
funpress (6):
- babel
- elm-by-example
- es6-features
- funpress.github.io
- mostly-adequate-guide-to-fp
- up-n-going
henrythemes (13):
- hello-jekyll-theme
- hello-minima-theme
- hello-pages-theme
- hello-pages-theme-v2
- jekyll-book-theme
- jekyll-boom-theme
- jekyll-boom-theme-v2
- jekyll-bootstrap-theme
- jekyll-gutenberg-theme
- jekyll-minimal-theme
- jekyll-starter-theme
- jekyll-starter-theme-v2
- jekyll-talks-theme
hybook (3):
- bookfile
- bookman
- hybook
hydepress (12):
- hydepress.github.io
- jekyll
- jekyll-deploy
- jekyll-dev
- jekyll-import
- jekyll-install
- jekyll-plugins
- jekyll-style
- jekyll-themes
- liquid
- octopod
- octopress
journaltxt (3):
- blog
- journaltxt
- journaltxt.github.io
json-next (5):
- awesome-json-next
- json-feed
- json-next
- json-next-tests
- json-next.github.io
manuscripts (3):
- book-starter
- manuscripts
- manuscripts.github.io
markupmadness (2):
- markupmadness
- markupmadness.github.io
mrhydescripts (2):
- mrhyde
- scripts
mundimark (13):
- awesome-books
- awesome-kramdown
- awesome-markdown
- awesome-markdown-alternatives
- awesome-markdown-editors
- markdown-can-i-use
- markdown-tools
- markdown-tools-books
- markdown-vs-latex
- markdown.pl
- mundimark.github.io
- quickrefs
- why-text
octobook (7):
- awesome-typography
- book-2017-theme
- book-2018-theme
- book-blank-theme
- book-classics-theme
- gitbook-to-octobook-sample
- octobook
officetxt (3):
- awesome-txt
- officetxt
- officetxt.github.io
openbeer (28):
- at-austria
- be-belgium
- by-bayern
- ca-canada
- ch-confoederatio-helvetica
- co-colorado
- collections
- cz-czech-republic
- datafile
- de-deutschland
- docs
- ie-ireland
- images
- jp-japan
- market
- menus
- mx-mexico
- nl-netherlands
- notes
- oberbayern
- oberfranken
- openbeer.github.io
- or-oregon
- schema
- schema.sql
- us-united-states
- wa-washington
- world
openblockchains (15):
- austrian-blockchain-whitepapers
- awesome-blockchains
- awesome-coins
- awesome-diem
- awesome-ico-truths
- awesome-tetherino
- bitcoin
- bitcoin-ponzi
- bitcon-books
- blockchain-whitepapers
- crypto-books
- crypto-quotes
- programming-bitcoin-script
- programming-blockchains
- tulips
openbookie (8):
- market.at-austria
- market.euro-cup
- market.europe-champions-league
- market.world-cup
- notes
- sport.db.market
- sport.db.play
- sportbook
openfootball (42):
- africa-cup
- austria
- club-world-cup
- clubs
- confed-cup
- copa-america
- copa-libertadores
- copa-sudamericana
- deutschland
- docs
- england
- espana
- euro
- euro.json
- europe
- europe-champions-league
- football.json
- fussball-de
- futbol-es
- help
- italy
- lang
- league-starter
- leagues
- mexico
- national-teams
- north-america-champions-league
- north-america-gold-cup
- opendata-theme
- openfootball.github.io
- players
- quick-starter
- schema
- schema.sql
- south-america
- spec
- stadiums
- women-euro-cup
- women-world-cup
- world
- worldcup
- worldcup.json
openmundi (12):
- austria.db
- datafile
- deutschland.db
- langs
- mundo-es
- notes
- openmundi.github.io
- welt-de
- wien.db
- world-heritage
- world.csv
- world.db
opensport (6):
- american-football.db
- formula1.db
- hockey.db
- opensport.github.io
- rugby.db
- ski.db
openwine (2):
- at-austria
- build
persondb (1):
- person.db.models
pixelartexchange (11):
- artbase
- artbase.server
- collections
- collections.meta
- currencycats.starter
- currencydodge.starter
- opensea.sandbox
- pixelart
- pixelart.blocks
- pixelart.gallery
- pixelart.howto
planet-templates (11):
- planet-blank
- planet-classic
- planet-digest
- planet-feeds
- planet-forty
- planet-hacker
- planet-news
- planet-paper
- planet-templates.github.io
- planet-top
- planet-zen
planetbeer (3):
- books
- planet
- planetbeer.github.io
planetjekyll (13):
- awesome-jekyll
- awesome-jekyll-editors
- awesome-jekyll-plugins
- awesome-jekyll-themes
- planet
- planetjekyll.github.io
- quickrefs
- sandbox
- sandbox-collections
- sandbox-github-pages
- sandbox-syntax-highlighter
- showcase
- snippets
planetopendata (6):
- awesome-austria
- awesome-football
- awesome-sqlite
- awesome-world
- planet
- planetopendata.github.io
planetruby (15):
- apps
- awesome
- awesome-rubies
- books
- books-old
- calendar-theme
- changes
- conferences
- gems
- hellohoe
- meetups
- planet
- planetruby.github.io
- quickrefs
- quiz
plutolive (3):
- pluto.admin
- pluto.live
- pluto.live.starter
publicdomainworks (1):
- publicdomainworks.github.io
quikstart (6):
- gem-starter-template
- gem-starter-template-hoe
- jekyll-starter-theme
- quik
- scripts
- sinatra-starter-template
rsssf (6):
- austria
- brazil
- deutschland
- england
- espana
- rsssf.github.io
rubycoco (15):
- activerecord
- blockchain
- core
- datasets
- events
- flow
- git
- markdown
- monos
- more
- programming-bits-bytes
- rubycoco.github.io
- text
- webclient
- webservice
s6ruby (12):
- ethereum-contracts
- pragmas
- programming-crypto-contracts
- redpaper
- ruby-to-michelson
- ruby-to-solidity
- safemath
- safestruct
- units-money
- units-time
- universum
- universum-contracts
schemadoc (2):
- schemadoc
- schemadoc-theme
shellpress (1):
- raspberrypi
slidekit (7):
- jekyll-talks-theme
- s6
- s6-minimalistic
- s6-samples
- s6-v1
- slidekit.github.io
- talks-starter
slideshow-s9 (9):
- awesome-slideshows
- demos
- docs
- samples
- slideshow
- slideshow-plugins
- slideshow-s9.github.io
- slideshow-service
- slideshow-starter
slideshow-templates (16):
- media
- slideshow-bespoke.js
- slideshow-csss
- slideshow-deck.js
- slideshow-google-html5-slides
- slideshow-google-io-2011-slides
- slideshow-impress.js
- slideshow-reveal.js
- slideshow-s5-blank
- slideshow-s5-themes
- slideshow-s6-blank
- slideshow-s6-blank-v1
- slideshow-s6-syntax-highlighter
- slideshow-shower
- slideshow-slidy
- slideshow-templates.github.io
sportdb (10):
- datasets
- docs
- football.db
- footty
- sport.db
- sport.db.admin
- sport.db.service
- sport.db.sources
- sport.db.web
- sportdb.github.io
sportkit (7):
- football.api.js
- football.html
- football.js
- football.js.starter
- sport.db.starter.go
- sport.db.starter.node.js
- sport.db.starter.ruby
sportlabs (1):
- major-league-soccer
sportlogos (6):
- football.db.logos
- football.db.logos.ruby
- hockey.db.logos
- sport.db.logos
- sport.db.logos.ruby
- sportlogos.github.io
staystatic (5):
- awesome-static
- quickrefs
- staystatic
- staystatic-starter
- staystatic.github.io
texti (3):
- pandoc
- texti
- texti.github.io
updownpress (2):
- markdown-lint
- updownpress.github.io
viennacrypto (1):
- viennacrypto.github.io
viennarb (3):
- planet
- questions
- viennarb.github.io
webstart (6):
- links
- manman
- upman
- upman-win
- webstart
- webstart.github.io
wikiscript (4):
- beer.json
- countries.json
- football.json
- wikiscript
worldbook (1):
- worldbook.github.io
worldclassics (3):
- dr-jekyll-and-mr-hyde
- the-trial
- worldclassics.github.io
worlddb (8):
- world.db
- world.db.admin
- world.db.cities
- world.db.codes
- world.db.flags
- world.db.service
- world.db.starter
- world.lite
yukimotopress (15):
- auto
- blockchains
- examples
- fizzbuzz
- gem-dev
- gem-tasks
- http
- langs
- micro
- practices
- practicing
- sinatra-intro
- smalldata
- start
- yukimotopress.github.io
