
name: Update datasets

on:
  schedule:
    # note: * is a special character in YAML so you have to quote this string
    #  see cron guru for more examples / help on syntax
    #    ->  https://crontab.guru/examples.html
    - cron:  '0 22 1,15 * *'       #  every 1 & 15 of the month at 22:00 (utc?)
  workflow_dispatch:
    ### for testing / debugging allow "manual" start


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Run install / adduser
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        bundle install
        # gem list
        # gem env
        yo adduser

    - name: Run setup / ssh_clone
      run:  yo clone

    ####
    # todo/check:
    #   split into "public" update
    #          and "private" traffic status update - why? why not?
    - name: Run get/fetch/update datatsets
      env:
        HUBBA_TOKEN: ${{ secrets.HUBBA_TOKEN }}
      run:  yo update

    - name: Run ssh_push
      run:  yo push
